---
version: "3.9"

services:
  ovos_skill_weather:
    container_name: ovos_skill_weather
    hostname: ovos_skill_weather
    restart: unless-stopped
    image: smartgic/ovos-skill-weather:${VERSION}
    pull_policy: always
    environment:
      TZ: $TZ
    network_mode: host
    ipc: host
    volumes:
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ${TMP_FOLDER}:/tmp/mycroft
    depends_on:
     - ovos_core

