---
version: "3.9"

services:
  ovos_phal:
    devices:
      - /dev/gpiomem
    group_add:
      - "$GPIO_GID"

  ovos_phal_admin:
    devices:
      - /dev/gpiomem
    group_add:
      - "$GPIO_GID"

  ovos_core:
    devices:
      - /dev/gpiomem
    group_add:
      - "$GPIO_GID"

#  ovos_gui:
#    devices:
#      - /dev/vchiq
#    group_add:
#      - $RENDER_GID
